{
 "title": "API monitoring",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  { "title": "Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Availability",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "WITH buckets AS (\n  SELECT generate_series($__timeFrom()::timestamptz,$__timeTo()::timestamptz, '10s'::interval) AS bucket_start\n),\nintervals AS (\n  SELECT\n    buckets.bucket_start AS ts,\n    COUNT(ts) AS nb_probes\n  FROM buckets\n  LEFT JOIN __POSTGRES_SCHEMA__.app_liveness ON ts > buckets.bucket_start AND ts <= buckets.bucket_start + interval '10s' \n  GROUP BY 1\n)\n\nSELECT\n  $__timeGroup(ts, $__interval) AS time,\n  AVG(\n    CASE\n      WHEN nb_probes > 0 THEN 100\n      ELSE 0\n    END\n  ) AS \"Availability\"\nFROM intervals\nGROUP BY 1\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "WITH buckets AS (\n  SELECT generate_series($__timeFrom()::timestamptz, $__timeTo()::timestamptz, '10s'::interval) AS bucket_start\n),\nintervals AS (\n  SELECT\n    buckets.bucket_start AS ts,\n    COUNT(ts) AS nb_probes\n  FROM buckets\n  LEFT JOIN __POSTGRES_SCHEMA__.app_liveness ON ts > buckets.bucket_start AND ts <= buckets.bucket_start + interval '10s' \n  GROUP BY 1\n),\nbucket_availability AS (\n  SELECT\n    $__timeGroup(ts, $__interval) AS bucket_start,\n    AVG(\n      CASE\n        WHEN nb_probes > 0 THEN 100\n        ELSE 0\n      END\n    ) AS availability\n  FROM intervals\n  GROUP BY 1\n)\n\nSELECT\n  to_timestamp(bucket_start) AS \"From\",\n  to_timestamp(bucket_start) + make_interval(secs => $__interval_ms / 1000) AS \"To\",\n  availability AS \"Availability\",\n  STRING_AGG(name, E'\\n') AS steps\nFROM bucket_availability\nLEFT JOIN __POSTGRES_SCHEMA__.run_step ON updated_ts > to_timestamp(bucket_start) AND created_ts <= to_timestamp(bucket_start) + make_interval(secs => $__interval_ms / 1000)\nGROUP BY 1, 2, 3"
    }
   ]
  },
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Avg duration",
   "type": "timeseries",
   "description": "Average duration in minutes when success",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(ts, $__interval) AS time,\n  MIN(duration_ms) AS \"3.min\",\n  AVG(duration_ms) AS \"2.avg\",\n  MAX(duration_ms) AS \"1.max\"\n\nFROM __POSTGRES_SCHEMA__.http_request_metrics\n\nWHERE\n  $__timeFilter(ts)\n\nGROUP BY 1\n\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Duration per endpoint",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT\n  method AS \"Method\",\n  path_template AS \"Endpoint\",\n  COUNT(ts) AS \"Nb requests\",\n  AVG(duration_ms) AS \"Average duration\",\n  MAX(duration_ms) AS \"Max duration\"\n\nFROM __POSTGRES_SCHEMA__.http_request_metrics\n\nWHERE\n  $__timeFilter(ts)\n\nGROUP BY 1, 2"
    }
   ]
  }
 ]
}