{
 "title": "Workflows monitoring",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  { "title": "Runs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Metrics",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(id) AS \"1. Nb runs\",\n  COUNT(id) FILTER (WHERE status = 'started') AS \"2. Nb started runs\",\n  COUNT(id) FILTER (WHERE status = 'succeeded') * 100 / NULLIF(COUNT(id), 0) AS \"3. Success rate\",\n  MAX(duration) FILTER (WHERE status = 'succeeded') AS \"4. Max duration\",\n  AVG(duration) FILTER (WHERE status = 'succeeded') AS \"5. Average duration\"\n\nFROM __POSTGRES_SCHEMA__.run\nWHERE \n  $__timeFilter(run.created_ts);"
    },
    {
     "rawSql": "SELECT\n  COALESCE(SUM(run_step.llm_cost), 0) AS \"LLM cost\"\n\nFROM __POSTGRES_SCHEMA__.run_step\nLEFT JOIN __POSTGRES_SCHEMA__.run ON run_step.run_id = run.id\nWHERE \n  $__timeFilter(run.created_ts);"
    }
   ]
  },
  {
   "title": "Status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(created_ts, $__interval) AS time,\n  COUNT(id) FILTER (WHERE status = 'succeeded') AS \"1. Succeded\",\n  COUNT(id) FILTER (WHERE status = 'failed') AS \"2. Failed\",\n  COUNT(id) FILTER (WHERE status = 'stopped') AS \"3. Stopped\",\n  COUNT(id) FILTER (WHERE status = 'started') AS \"4. Started\"\nFROM __POSTGRES_SCHEMA__.run\nWHERE \n  $__timeFilter(run.created_ts)\nGROUP BY 1\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Avg duration",
   "type": "timeseries",
   "description": "Average duration in minutes when success",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(created_ts, $__interval) AS time,\n  MIN(duration) AS \"3.min\",\n  AVG(duration) AS \"2.avg\",\n  MAX(duration) AS \"1.max\"\nFROM __POSTGRES_SCHEMA__.run\nWHERE \n  status = 'succeeded'\nAND $__timeFilter(run.created_ts)\nGROUP BY 1\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Started runs",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "WITH run_cte AS (\n  SELECT \n    run.id,\n    run.id AS run_id,\n    run.status AS status,\n    \"user\".full_name AS user_full_name,\n    run.created_ts AS created_ts\n    \n  FROM __POSTGRES_SCHEMA__.run\n  LEFT JOIN __POSTGRES_SCHEMA__.\"user\" ON run.creator_id = \"user\".id\n  WHERE \n    $__timeFilter(run.created_ts)\n    AND run.status = 'started'\n),\nrun_step_cte AS (\n  SELECT \n    run_id,\n    COUNT(id) AS nb_steps,\n    COUNT(id) FILTER (WHERE status = 'started') AS nb_started_steps,\n    STRING_AGG(\n      name ||\n      ' - ' ||\n      status ||\n      ' - Updated ' ||\n      FLOOR(EXTRACT(EPOCH FROM (NOW() - updated_ts)) / 60)::int ||\n      ' min ' ||\n      (EXTRACT(EPOCH FROM (NOW() - updated_ts))::int % 60)::int ||\n      ' sec ago', \n      E'\\n'\n    ) FILTER (WHERE status IN ('started', 'pending')) AS started_steps\n\n  FROM __POSTGRES_SCHEMA__.run_step\n  WHERE\n    run_id IN (SELECT id FROM run_cte)\n  GROUP BY run_id\n)\n\nSELECT \n  run_cte.run_id AS \"Run ID\",\n  run_cte.status AS \"Run status\",\n  run_cte.user_full_name AS \"Run by\",\n  run_cte.created_ts AS \"Created ts\",\n  nb_steps AS \"Nb steps\",\n  nb_started_steps AS \"Nb started steps\",\n  started_steps AS \"Started steps\"\n  \nFROM run_cte\nLEFT JOIN run_step_cte ON run_step_cte.run_id = run_cte.id\n;"
    }
   ]
  },
  {
   "title": "Failed runs",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "rawSql": "WITH run_cte AS (\n  SELECT \n    run.id,\n    run.id AS run_id,\n    run.status AS status,\n    \"user\".full_name AS user_full_name,\n    run.created_ts AS created_ts\n    \n  FROM __POSTGRES_SCHEMA__.run\n  LEFT JOIN __POSTGRES_SCHEMA__.\"user\" ON run.creator_id = \"user\".id\n  WHERE \n    $__timeFilter(run.created_ts)\n    AND run.status = 'failed'\n),\nrun_step_cte AS (\n  SELECT \n    run_id,\n    COUNT(id) AS nb_steps,\n    COUNT(id) FILTER (WHERE status = 'failed') AS nb_failed_steps,\n    STRING_AGG(name, E'\\n') FILTER (WHERE status = 'failed') AS failed_steps\n\n  FROM __POSTGRES_SCHEMA__.run_step\n  WHERE\n    run_id IN (SELECT id FROM run_cte)\n  GROUP BY run_id\n)\n\nSELECT \n  run_cte.run_id AS \"Run ID\",\n  run_cte.status AS \"Run status\",\n  run_cte.user_full_name AS \"Run by\",\n  run_cte.created_ts,\n  nb_steps AS \"Nb steps\",\n  nb_failed_steps AS \"Nb failed steps\",\n  failed_steps AS \"Failed steps\"\n  \nFROM run_cte\nLEFT JOIN run_step_cte ON run_step_cte.run_id = run_cte.id\n;"
    }
   ]
  },
  {
   "title": "Started and pending steps",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "rawSql": "SELECT\n  run_step.run_id AS \"Run ID\",\n  run.status AS \"Run status\",\n  run_step.description AS \"Step\",\n  run_step.status AS \"Step status\",\n  run_step.updated_ts AS \"Step updated ts\",\n  run_step.logs AS \"Logs\"\n  \nFROM __POSTGRES_SCHEMA__.run_step\nLEFT JOIN __POSTGRES_SCHEMA__.run ON run_step.run_id = run.id\nWHERE \n  $__timeFilter(run.created_ts)\n  AND run_step.status IN ('started', 'pending')\n;"
    }
   ]
  },
  {
   "title": "Failed steps",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "rawSql": "SELECT\n  run_step.run_id AS \"Run ID\",\n  run.status AS \"Run status\",\n  run_step.description AS \"Step\",\n  run_step.status AS \"Step status\",\n  run_step.updated_ts AS \"Step updated ts\",\n  run_step.logs AS \"Logs\"\n  \nFROM __POSTGRES_SCHEMA__.run_step\nLEFT JOIN __POSTGRES_SCHEMA__.run ON run_step.run_id = run.id\nWHERE \n  $__timeFilter(run.created_ts)\n  AND run_step.status = 'failed'\n;"
    }
   ]
  },
  {
   "title": "Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "Runs",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 54 },
     "targets": [
      {
       "rawSql": "SELECT\n  COUNT(run.id) AS \"Nb runs\",\n  COUNT(run.id) FILTER (WHERE run.status = 'failed') AS \"Failed runs\",\n  COUNT(run.id) FILTER (WHERE run.status = 'succeeded') * 100 / NULLIF(COUNT(run.id), 0) AS \"Success rate\",\n  AVG(run.duration) FILTER (WHERE run.status = 'succeeded') AS \"Average duration\",\n  MAX(run.duration) FILTER (WHERE run.status = 'succeeded') AS \"Max duration\"\n  \nFROM __POSTGRES_SCHEMA__.run\nWHERE \n  $__timeFilter(run.created_ts);"
      }
     ]
    }
   ]
  },
  {
   "title": "Steps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 55 },
     "targets": [
      {
       "rawSql": "SELECT\n  run_step.description,\n  COUNT(run_step.id) FILTER (WHERE run_step.status = 'succeeded') * 100 / NULLIF(COUNT(run.id), 0) AS \"Success rate\",\n  AVG(run_step.duration) FILTER (WHERE run_step.status = 'succeeded') AS \"Average duration\",\n  MAX(run_step.duration) FILTER (WHERE run_step.status = 'succeeded') AS \"Max duration\",\n  AVG(run_step.llm_cost) FILTER (WHERE run_step.status = 'succeeded') AS \"Average LLM cost\",\n  MAX(run_step.llm_cost) FILTER (WHERE run_step.status = 'succeeded') AS \"Max LLM cost\",\n  COUNT(run_step.id) AS \"Nb runs\",\n  COUNT(run_step.id) FILTER (WHERE run_step.status = 'failed') AS \"Failed runs\"\n  \nFROM __POSTGRES_SCHEMA__.run_step\nLEFT JOIN __POSTGRES_SCHEMA__.run ON run_step.run_id = run.id\nWHERE \n  $__timeFilter(run.created_ts)\n  AND run_step.description NOT LIKE 'Generate Requirements for document id%' -- Legacy steps\n  AND run_step.description NOT LIKE 'Gap Analysis for run id%' -- Legacy steps\n  AND run_step.description NOT LIKE 'Generate Summary for document id%' -- Legacy steps\n  AND run_step.description NOT LIKE 'Generate Typology and Summary for document id%' -- Legacy steps\nGROUP BY 1;"
      }
     ]
    },
    {
     "title": "Logs",
     "type": "table",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 64 },
     "targets": [
      {
       "rawSql": "SELECT\n  run.id AS \"Run ID\",\n  run.status AS \"Run status\",\n  run_step.description AS \"Step\",\n  run_step.status AS \"Step status\",\n  run_step.created_ts AS \"Step created ts\",\n  run_step.logs AS \"Logs\"\n  \nFROM __POSTGRES_SCHEMA__.run_step\nLEFT JOIN __POSTGRES_SCHEMA__.run ON run_step.run_id = run.id\nWHERE \n  $__timeFilter(run.created_ts)\n;"
      }
     ]
    }
   ]
  }
 ]
}