/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NotesIndexRouteImport } from './routes/notes.index'
import { Route as NotesUpdatesRouteImport } from './routes/notes.updates'
import { Route as NotesActionsRouteImport } from './routes/notes.actions'
import { Route as NotesNoteIdRouteImport } from './routes/notes.$noteId'

const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesIndexRoute = NotesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NotesRoute,
} as any)
const NotesUpdatesRoute = NotesUpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => NotesRoute,
} as any)
const NotesActionsRoute = NotesActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => NotesRoute,
} as any)
const NotesNoteIdRoute = NotesNoteIdRouteImport.update({
  id: '/$noteId',
  path: '/$noteId',
  getParentRoute: () => NotesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRouteWithChildren
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/notes/actions': typeof NotesActionsRoute
  '/notes/updates': typeof NotesUpdatesRoute
  '/notes/': typeof NotesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/notes/actions': typeof NotesActionsRoute
  '/notes/updates': typeof NotesUpdatesRoute
  '/notes': typeof NotesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRouteWithChildren
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/notes/actions': typeof NotesActionsRoute
  '/notes/updates': typeof NotesUpdatesRoute
  '/notes/': typeof NotesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/notes'
    | '/notes/$noteId'
    | '/notes/actions'
    | '/notes/updates'
    | '/notes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/notes/$noteId'
    | '/notes/actions'
    | '/notes/updates'
    | '/notes'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/notes'
    | '/notes/$noteId'
    | '/notes/actions'
    | '/notes/updates'
    | '/notes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  NotesRoute: typeof NotesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/': {
      id: '/notes/'
      path: '/'
      fullPath: '/notes/'
      preLoaderRoute: typeof NotesIndexRouteImport
      parentRoute: typeof NotesRoute
    }
    '/notes/updates': {
      id: '/notes/updates'
      path: '/updates'
      fullPath: '/notes/updates'
      preLoaderRoute: typeof NotesUpdatesRouteImport
      parentRoute: typeof NotesRoute
    }
    '/notes/actions': {
      id: '/notes/actions'
      path: '/actions'
      fullPath: '/notes/actions'
      preLoaderRoute: typeof NotesActionsRouteImport
      parentRoute: typeof NotesRoute
    }
    '/notes/$noteId': {
      id: '/notes/$noteId'
      path: '/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof NotesNoteIdRouteImport
      parentRoute: typeof NotesRoute
    }
  }
}

interface NotesRouteChildren {
  NotesNoteIdRoute: typeof NotesNoteIdRoute
  NotesActionsRoute: typeof NotesActionsRoute
  NotesUpdatesRoute: typeof NotesUpdatesRoute
  NotesIndexRoute: typeof NotesIndexRoute
}

const NotesRouteChildren: NotesRouteChildren = {
  NotesNoteIdRoute: NotesNoteIdRoute,
  NotesActionsRoute: NotesActionsRoute,
  NotesUpdatesRoute: NotesUpdatesRoute,
  NotesIndexRoute: NotesIndexRoute,
}

const NotesRouteWithChildren = NotesRoute._addFileChildren(NotesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  NotesRoute: NotesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
